# Generated by Django 3.0.3 on 2020-02-13 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick', models.BooleanField()),
                ('chosen_time', models.TimeField()),
                ('pgn', models.CharField(blank=True, max_length=2000)),
                ('black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_black', to=settings.AUTH_USER_MODEL)),
                ('white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndedMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Match')),
                ('result', models.CharField(max_length=3)),
            ],
            bases=('game.match',),
        ),
        migrations.CreateModel(
            name='InMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Match')),
                ('white_turn', models.BooleanField(default=True)),
                ('last_move', models.DateTimeField(auto_now=True)),
            ],
            bases=('game.match',),
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Match')),
                ('random_color', models.BooleanField(default=False)),
            ],
            bases=('game.match',),
        ),
        migrations.CreateModel(
            name='RankUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuickMatch',
            fields=[
                ('inmatch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.InMatch')),
                ('white_time', models.TimeField()),
                ('black_time', models.TimeField()),
            ],
            bases=('game.inmatch',),
        ),
    ]
