# Generated by Django 3.0.3 on 2020-02-14 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmatch',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 16, 28, 45, 745199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='match',
            name='chosen_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='quickmatch',
            name='black_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='quickmatch',
            name='white_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
