# Generated by Django 3.0.3 on 2020-02-14 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200214_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmatch',
            name='last_move',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 14, 16, 31, 15, 686072, tzinfo=utc)),
        ),
    ]
