# Generated by Django 3.0.3 on 2020-02-14 16:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200214_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmatch',
            name='last_move',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quickmatch',
            name='black_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='quickmatch',
            name='white_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
