# Generated by Django 3.0.3 on 2020-02-14 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200214_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickmatch',
            name='black_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='quickmatch',
            name='white_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
