# Generated by Django 3.0.3 on 2020-02-19 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_auto_20200214_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RankUser',
            new_name='Profile',
        ),
    ]
