# Generated by Django 3.0.3 on 2020-03-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200301_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='endedmatch',
            name='last_fen',
            field=models.CharField(default='', max_length=70),
        ),
    ]
