# Generated by Django 3.0.3 on 2020-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_endedmatch_last_fen'),
    ]

    operations = [
        migrations.AddField(
            model_name='endedmatch',
            name='end_reason',
            field=models.CharField(default='', max_length=50),
        ),
    ]
