# Generated by Django 3.0.3 on 2020-03-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_endedmatch_end_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notify_black',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='notify_white',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='endedmatch',
            name='result',
            field=models.CharField(default='*', max_length=10),
        ),
    ]
