# Generated by Django 3.0.3 on 2020-03-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20200305_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='notify_black',
        ),
        migrations.RemoveField(
            model_name='match',
            name='notify_white',
        ),
    ]
