# Generated by Django 3.0.3 on 2020-03-08 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20200305_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='endedmatch',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
