# Generated by Django 3.0.3 on 2020-03-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_endedmatch_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expo_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
